// Code generated by goctl. DO NOT EDIT.
package types

type Reply struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data,omitempty"`
}

type JwtTokenRequest struct {
}

type JwtTokenInfo struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
	RefreshAfter int64  `json:"refresh_after"` // 建议客户端刷新token的绝对时间
}

type SongsheetListReq struct {
}

type SongsheetListItem struct {
	Id            string `json:"id"`
	Name          string `json:"name"`
	CreatedAt     string `json:"created_at"`
	UpdatedAt     string `json:"updated_at"`
	DataUpdatedAt string `json:"data_updated_at"`
}

type SongsheetSongListReq struct {
	Id string `path:"id"`
}

type SongListItem struct {
	Id            string `json:"id"`
	Name          string `json:"name"`
	Ext           string `json:"ext"`
	SongLocalPath string `json:"song_local_path"`
	SongRoutePath string `json:"song_route_path"`
	LyricText     string `json:"lyric_text"`
	CreatedAt     string `json:"created_at"`
	UpdatedAt     string `json:"updated_at"`
	DataUpdatedAt string `json:"data_updated_at"`
}

type SongListReq struct {
}

type SongDetailReq struct {
	Id string `path:"id"`
}
